pipeline {
    agent any
    
    stages {
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage('Checkout') {
            steps {
                // Đặt đường dẫn của mã nguồn chương trình C
                sh "git clone https://github.com/cuongmaidt2/Command_Line_Arguments.git"
            }
        }
        
        stage('Build') {
            steps {
                // Thực hiện các lệnh build chương trình C
                sh '''
                cd /var/jenkins_home/workspace/Command_Line_Arguments/Command_Line_Arguments
                gcc -o Command_Line_Arguments Command_Line_Arguments.c
                '''
            }
        }
        
        stage('Test') {
            steps {
                // Thực hiện các lệnh kiểm tra chương trình C
                sh '''
                cd /var/jenkins_home/workspace/Command_Line_Arguments/Command_Line_Arguments
                ./Command_Line_Arguments Argv1 Argv2
                '''
            }
        }

        stage('Push') {
            steps {
                // Thực hiện các push file đã biên dịch lên GIT
                sh '''
                git config --global credential.helper store
                git config --global user.name "maicuong.qt212@gmail.com"
                git config --global user.email "maicuong.qt212@gmail.com"
                cd /var/jenkins_home/workspace/Command_Line_Arguments/Command_Line_Arguments
                git add Command_Line_Arguments
                git commit -m "Command_Line_Arguments"
                git push -u origin "https://$GH_TOKEN@github.com/cuongmaidt2/Command_Line_Arguments.git"
                git push -u origin main
                '''
            }
        }
    }
}
